In [21]:
#Q1: Create a NumPy array of 100 random numbers and calculate all key statistics (mean, median, std, min, max) in one script.

import numpy as np

import pandas as pd

array = np.random.randint(0,500,100)



mean = np.mean(array)
median = np.median(array)
std = np.std(array)
min = np.min(array)
max = np.max(array)

print("\n--- Statistics ---")
print("Mean   :", mean)
print("Median :", median)
print("Standard Deviation :", std)
print("Minimum:", min)
print("Maximum:", max)

--- Statistics ---
Mean   : 249.58
Median : 238.5
Standard Deviation : 134.06387880409847
Minimum: 5
Maximum: 497

In [2]:
array

array([198, 374, 368,  13, 381, 458, 139, 177, 304,  19, 169, 318, 121,
       450,  14, 362, 453, 256, 405, 136, 247, 375,  41, 295,  69, 243,
       197, 341, 362, 217, 121, 291, 211, 155, 243, 495,  51, 430, 390,
       134, 364, 218, 161, 317, 202, 318, 318, 331, 139, 291,  39,  46,
        29, 124,  25,  13,  91, 313, 282,  81, 214,  62,  39, 143,  22,
       296, 361, 303,  58, 440,  93, 381, 257,  62, 261, 163, 302, 239,
       226, 295,  50,  48, 298, 430,  89, 381, 301, 444, 438, 395,  61,
        31,  21, 248, 408, 374, 356,  26, 471, 202], dtype=int32)

In [3]:
#Q2: Load the Titanic dataset and print a full data summary: shape, dtypes, missing values, and describe().

import seaborn as sns

titanic = sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
titanic.shape

(891, 15)

In [5]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [6]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
#Q3: Clean the Titanic dataset: handle missing Age and Embarked values, drop irrelevant columns.

titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
titanic["age"] = titanic["age"].fillna(titanic["age"].median)

titanic["embark_town"] = titanic["embark_town"].fillna(titanic["embark_town"].mode()[0])

In [12]:
titanic.drop(columns=["who","deck"],inplace=True)

In [14]:
titanic["embarked"] = titanic["embarked"].fillna(titanic["embarked"].mode)

In [15]:
titanic.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [18]:
#Q4: Find the survival rate (%) by gender using groupby().

survival_rate = titanic.groupby("sex")["survived"].mean() *100

survival_rate

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [20]:
#Q5: Find the survival rate (%) by passenger class (Pclass) using groupby().

survival_rate = titanic.groupby("pclass")["survived"].mean()*100

survival_rate

pclass
1    62.962963
2    47.282609
3    24.236253
Name: survived, dtype: float64