In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Data Analyst 2.0\Python Projects\Day 13\day13_sales_dataset_1000_rows.csv")

In [4]:
data

,OrderID,OrderDate,Month,Region,Product,Category,SalesPerson,Quantity,UnitPrice,Sales
0,1,2024-11-29,November,North,Tablet,Electronics,Riya,5,5000,25000
1,2,2024-10-25,October,North,Keyboard,Accessories,Rahul,4,1200,4800
2,3,2024-08-02,August,North,Laptop,Electronics,Rahul,3,5000,15000
3,4,2024-01-31,January,North,Laptop,Electronics,Rahul,18,5000,90000
4,5,2024-10-22,October,West,Mouse,Accessories,Amit,19,500,9500
...,...,...,...,...,...,...,...,...,...,...
995,996,2024-03-05,March,East,Laptop,Electronics,Amit,6,15000,90000
996,997,2024-03-04,March,North,Laptop,Electronics,Amit,2,800,1600
997,998,2024-08-25,August,South,Tablet,Electronics,Riya,6,500,3000
998,999,2024-07-02,July,South,Phone,Electronics,Vikas,7,15000,105000
999,1000,2024-07-19,July,West,Laptop,Electronics,Sneha,14,1200,16800

In [5]:
#Q1: Group a sales DataFrame by 'Region' and calculate total sales per region using groupby().sum().

region_sales = data.groupby("Region")["Sales"].sum()

region_sales

Region
East     22166100
North    18996000
South    31351900
West     19690700
Name: Sales, dtype: int64

In [6]:
#Q2: Group data by a categorical column and calculate mean, median, and count simultaneously using agg().

result = data.groupby("Category")["Sales"].agg(["mean", "median", "count"])

result

                     mean   median  count
Category
Accessories  95512.552301  19200.0    478
Electronics  89175.670498  15600.0    522

In [7]:
#Q3: Group by two columns (e.g., Region and Product) and calculate total sales for each combination.

result = data.groupby(["Region","Product"]).sum("Sales")

In [8]:
result

                 OrderID  Quantity  UnitPrice    Sales
Region Product
East   Keyboard    12832       365     299100  2696800
       Laptop      26341       612     392200  4342200
       Monitor     24723       510     383900  4212700
       Mouse       21064       344     282700  2827100
       Phone       25336       508     423900  4473400
       Tablet      19352       426     339500  3613900
North  Keyboard    20407       358     232700  2054000
       Laptop      23487       456     290400  3301300
       Monitor     18693       427     218500  2470500
       Mouse       16632       372     283600  3396400
       Phone       20801       391     334100  3859300
       Tablet      17443       388     331200  3914500
South  Keyboard    20714       469     306800  3539900
       Laptop      22689       394     298800  2993100
       Monitor     26623       639     583300  6909300
       Mouse       23681       521     625200  8082900
       Phone       24078       523     409700  4419800
       Tablet      20246       545     481200  5406900
West   Keyboard    18859       362     278900  2788400
       Laptop      23753       414     282800  2567100
       Monitor     17194       378     268200  2789200
       Mouse       21102       398     357000  3887800
       Phone       14556       302     302100  2719500
       Tablet      19894       452     404700  4938700

In [9]:
#Q4: Find the top 5 highest-selling products using groupby() and sort_values().

result = data.groupby("Product")["Sales"].sum().sort_values(ascending = False).head()

result

Product
Mouse      18194200
Tablet     17874000
Monitor    16381700
Phone      15472000
Laptop     13203700
Name: Sales, dtype: int64

In [10]:
#Q5: Use value_counts() to find the frequency of each category in a column.

result = data.value_counts("Category")

result

Category
Electronics    522
Accessories    478
Name: count, dtype: int64

In [11]:
data

,OrderID,OrderDate,Month,Region,Product,Category,SalesPerson,Quantity,UnitPrice,Sales
0,1,2024-11-29,November,North,Tablet,Electronics,Riya,5,5000,25000
1,2,2024-10-25,October,North,Keyboard,Accessories,Rahul,4,1200,4800
2,3,2024-08-02,August,North,Laptop,Electronics,Rahul,3,5000,15000
3,4,2024-01-31,January,North,Laptop,Electronics,Rahul,18,5000,90000
4,5,2024-10-22,October,West,Mouse,Accessories,Amit,19,500,9500
...,...,...,...,...,...,...,...,...,...,...
995,996,2024-03-05,March,East,Laptop,Electronics,Amit,6,15000,90000
996,997,2024-03-04,March,North,Laptop,Electronics,Amit,2,800,1600
997,998,2024-08-25,August,South,Tablet,Electronics,Riya,6,500,3000
998,999,2024-07-02,July,South,Phone,Electronics,Vikas,7,15000,105000
999,1000,2024-07-19,July,West,Laptop,Electronics,Sneha,14,1200,16800

In [12]:
#Q6: Sort a DataFrame by multiple columns with different ascending/descending order for each.

result = data.sort_values(by=["Region","Sales"],ascending = False)

result

,OrderID,OrderDate,Month,Region,Product,Category,SalesPerson,Quantity,UnitPrice,Sales
259,260,2024-01-16,January,West,Tablet,Electronics,Amit,20,30000,600000
333,334,2024-07-26,July,West,Monitor,Accessories,Riya,19,30000,570000
343,344,2024-08-12,August,West,Tablet,Electronics,Neha,19,30000,570000
522,523,2024-12-27,December,West,Laptop,Electronics,Amit,19,30000,570000
797,798,2024-12-16,December,West,Keyboard,Accessories,Riya,19,30000,570000
...,...,...,...,...,...,...,...,...,...,...
242,243,2024-06-20,June,East,Phone,Electronics,Amit,2,500,1000
303,304,2024-10-16,October,East,Monitor,Accessories,Neha,2,500,1000
366,367,2024-10-12,October,East,Laptop,Electronics,Karan,2,500,1000
584,585,2024-11-16,November,East,Monitor,Accessories,Karan,2,500,1000
937,938,2024-10-21,October,East,Laptop,Electronics,Amit,1,800,800

In [13]:
#Q7: Filter a DataFrame to show only rows where a group's total exceeds a threshold.

result = data.groupby("Product")["Sales"].sum()

result= result[result > 12200000]

result

Product
Laptop     13203700
Monitor    16381700
Mouse      18194200
Phone      15472000
Tablet     17874000
Name: Sales, dtype: int64

In [14]:
#Q8: Use groupby() with agg() to apply different aggregation functions to different columns.

result = data.groupby("Category").agg({
    "Sales":"sum",
    "Quantity" : "mean",
    "UnitPrice" : "max"

})

result

                Sales   Quantity  UnitPrice
Category
Accessories  45655000  10.759414      30000
Electronics  46549700  10.365900      30000

In [15]:
#Q9: Calculate the percentage contribution of each group to the overall total.

result = data.groupby("Region")["Sales"].sum()/data["Sales"].sum()*100

result

Region
East     24.040098
North    20.601987
South    34.002497
West     21.355419
Name: Sales, dtype: float64

In [16]:
#Q10: Use pivot_table() to create a summary table of sales by Region and Month.

result = data.pivot_table(
    values="Sales",
    index="Region",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)

result

Month,April,August,December,February,January,July,June,March,May,November,October,September
Region,,,,,,,,,,,,
East,2551500,1916300,1864900,946100,2633800,1824400,1210100,1539100,1338300,1993000,1141300,3207300
North,1361500,897800,1781200,1558400,2406300,1559200,3593600,1372500,1012500,1578100,821800,1053100
South,3578600,2098100,1567900,3301700,2150400,3327400,3242900,3139600,1457100,2984200,2939900,1564100
West,1134500,1680300,2592000,1717400,1640400,1904000,1076500,3048600,1940100,1095700,1412500,448700

In [17]:
#Q11: Rank rows within each group using groupby() and rank().

data["Rank"] = data.groupby("Region")["Sales"].rank(ascending=True).astype(int)
result

Month,April,August,December,February,January,July,June,March,May,November,October,September
Region,,,,,,,,,,,,
East,2551500,1916300,1864900,946100,2633800,1824400,1210100,1539100,1338300,1993000,1141300,3207300
North,1361500,897800,1781200,1558400,2406300,1559200,3593600,1372500,1012500,1578100,821800,1053100
South,3578600,2098100,1567900,3301700,2150400,3327400,3242900,3139600,1457100,2984200,2939900,1564100
West,1134500,1680300,2592000,1717400,1640400,1904000,1076500,3048600,1940100,1095700,1412500,448700

In [18]:
#Q13: Filter groups that have more than N rows using groupby().filter().

result = data.groupby("Month")["Sales"].filter(lambda x: len(x) > 150)

In [19]:
result

Series([], Name: Sales, dtype: int64)

In [20]:
#Q15: Create a cumulative sum within each group using groupby().cumsum().

result = data.groupby("Region")["Sales"].cumsum()

In [21]:
result

0         25000
1         29800
2         44800
3        134800
4          9500
         ...
995    22166100
996    18996000
997    31246900
998    31351900
999    19690700
Name: Sales, Length: 1000, dtype: int64

In [22]:
#Q16: Use nlargest() and nsmallest() to find the top and bottom N rows by a column

result = data.nlargest(5,"Sales")

In [23]:
result

,OrderID,OrderDate,Month,Region,Product,Category,SalesPerson,Quantity,UnitPrice,Sales,Rank
113,114,2024-09-17,September,East,Phone,Electronics,Riya,20,30000,600000,253
184,185,2024-11-13,November,East,Laptop,Electronics,Rahul,20,30000,600000,253
200,201,2024-03-23,March,South,Mouse,Accessories,Priya,20,30000,600000,282
227,228,2024-01-24,January,North,Phone,Electronics,Amit,20,30000,600000,237
259,260,2024-01-16,January,West,Tablet,Electronics,Amit,20,30000,600000,224

In [26]:
result = data.nsmallest(10,"Quantity")

result

,OrderID,OrderDate,Month,Region,Product,Category,SalesPerson,Quantity,UnitPrice,Sales,Rank
48,49,2024-10-29,October,West,Phone,Electronics,Neha,1,800,800,3
77,78,2024-10-10,October,West,Monitor,Accessories,Sneha,1,1200,1200,7
82,83,2024-09-15,September,South,Laptop,Electronics,Karan,1,500,500,2
93,94,2024-05-15,May,North,Keyboard,Accessories,Neha,1,500,500,4
136,137,2024-01-17,January,West,Tablet,Electronics,Karan,1,800,800,3
158,159,2024-05-23,May,North,Laptop,Electronics,Vikas,1,500,500,4
207,208,2024-09-07,September,West,Laptop,Electronics,Rahul,1,15000,15000,102
250,251,2024-02-24,February,South,Laptop,Electronics,Vikas,1,500,500,2
251,252,2024-01-22,January,South,Phone,Electronics,Amit,1,500,500,2
262,263,2024-04-13,April,East,Monitor,Accessories,Amit,1,15000,15000,117

In [35]:
#Q17: Filter a DataFrame using the query() method instead of boolean indexing.

result = data.query("Sales > 550000")

result

,OrderID,OrderDate,Month,Region,Product,Category,SalesPerson,Quantity,UnitPrice,Sales,Rank
98,99,2024-12-15,December,South,Mouse,Accessories,Riya,19,30000,570000,279
113,114,2024-09-17,September,East,Phone,Electronics,Riya,20,30000,600000,253
184,185,2024-11-13,November,East,Laptop,Electronics,Rahul,20,30000,600000,253
200,201,2024-03-23,March,South,Mouse,Accessories,Priya,20,30000,600000,282
227,228,2024-01-24,January,North,Phone,Electronics,Amit,20,30000,600000,237
259,260,2024-01-16,January,West,Tablet,Electronics,Amit,20,30000,600000,224
327,328,2024-02-12,February,South,Mouse,Accessories,Amit,20,30000,600000,282
333,334,2024-07-26,July,West,Monitor,Accessories,Riya,19,30000,570000,221
343,344,2024-08-12,August,West,Tablet,Electronics,Neha,19,30000,570000,221
453,454,2024-11-21,November,North,Tablet,Electronics,Priya,19,30000,570000,235
522,523,2024-12-27,December,West,Laptop,Electronics,Amit,19,30000,570000,221
524,525,2024-02-11,February,South,Keyboard,Accessories,Rahul,19,30000,570000,279
583,584,2024-06-21,June,South,Monitor,Accessories,Amit,20,30000,600000,282
586,587,2024-06-09,June,North,Tablet,Electronics,Priya,19,30000,570000,235
707,708,2024-03-30,March,East,Phone,Electronics,Vikas,20,30000,600000,253
719,720,2024-12-29,December,North,Monitor,Accessories,Priya,19,30000,570000,235
741,742,2024-05-23,May,South,Phone,Electronics,Sneha,19,30000,570000,279
782,783,2024-01-09,January,North,Mouse,Accessories,Vikas,20,30000,600000,237
797,798,2024-12-16,December,West,Keyboard,Accessories,Riya,19,30000,570000,221
968,969,2024-04-20,April,East,Mouse,Accessories,Priya,20,30000,600000,253

In [41]:
#Q18: Group data by date (e.g., by Month) after converting a column to datetime, and calculate monthly totals.

data.dtypes

OrderID                 int64
OrderDate      datetime64[ns]
Month                  object
Region                 object
Product                object
Category               object
SalesPerson            object
Quantity                int64
UnitPrice               int64
Sales                   int64
Rank                    int64
dtype: object

In [40]:
data["OrderDate"] = pd.to_datetime(data["OrderDate"])

In [45]:
result = data.groupby(data["OrderDate"].dt.month)["Sales"].sum()

result

OrderDate
1     8830900
2     7523600
3     9099800
4     8626100
5     5748000
6     9123100
7     8615000
8     6592500
9     6273200
10    6315500
11    7651000
12    7806000
Name: Sales, dtype: int64

In [47]:
#Q20: Build a complete sales summary report: total, average, and count of orders by region and product category.

report = data.groupby(["Region","Category"]).agg(
    Total_Sales = ("Sales","sum"),
    Average_Sales = ("Sales","mean"),
    Order_Count = ("OrderID","count")
)

report

                    Total_Sales  Average_Sales  Order_Count
Region Category
East   Accessories      9736600   84666.086957          115
       Electronics     12429500   88782.142857          140
North  Accessories      7920900   71359.459459          111
       Electronics     11075100   87205.511811          127
South  Accessories     18532100  128695.138889          144
       Electronics     12819800   92228.776978          139
West   Accessories      9465400   87642.592593          108
       Electronics     10225300   88149.137931          116